# GitHub Pages configuration
# This file is not strictly necessary when using Quarto, but can help with GitHub Pages

# Exclude files from GitHub Pages processing
exclude:
  - poetry.lock
  - pyproject.toml
  - scripts/
  - fuseki/
  - docs/
  - .github/
  - "*.sh"
  - "*.py"
  - content/
  - ontology/

# Include the built site
include:
  - _site/

# Disable Jekyll processing (we're using Quarto)
plugins: []
