project:
  type: website
  title: "Mathematics Knowledge Graph Wiki"
  output-dir: _site
  render:
    - "*.qmd"
    - "content/"
    - "!design_EN/"
    - "!design_JA/"
    - "!docs/design_EN/"

website:
  title: "Math Knowledge Graph"
  favicon: favicon.ico
  navbar:
    right:
      - icon: github
        href: https://github.com/RK0429/ModernMath
        aria-label: github
  sidebar:
    - id: algebra
      title: "Algebra"
      contents:
        - content/algebra/*.qmd
    - id: analysis
      title: "Analysis"
      contents:
        - content/analysis/*.qmd
    - id: topology
      title: "Topology"
      contents:
        - content/topology/*.qmd
  page-footer:
    center: |
      Mathematics Knowledge Graph Wiki - Built with Quarto and RDF

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-copy: true
    code-overflow: wrap
    html-math-method: mathjax
    mathjax:
      tags: ams
      macros:
        R: '\mathbb{R}'
        Z: '\mathbb{Z}'
        N: '\mathbb{N}'
        C: '\mathbb{C}'
        Q: '\mathbb{Q}'
        implies: '\Rightarrow'
        iff: '\Leftrightarrow'
  # PDF generation disabled for performance reasons
  # To enable PDF generation, uncomment the following lines:
  # pdf:
  #   documentclass: article
  #   papersize: a4
  #   fontsize: 11pt
  #   geometry:
  #     - margin=1in
  #   include-in-header:
  #     - text: |
  #         \usepackage{amsmath,amssymb,amsthm}
  #         \usepackage{mathtools}
  #         \usepackage{unicode-math}

filters:
  - math-environments
  - graph-viz
  - translation-metadata
  - article-type

execute:
  freeze: auto

bibliography: references.bib

resources:
  - knowledge_graph.ttl
  - .nojekyll
  - output/interactive
  - output/d3-data
  - js
