project:
  type: website
  title: "Mathematics Knowledge Graph Wiki"
  output-dir: _site/en
  render:
    - "*.qmd"
    - "content/en/"
    - "!content/ja/"
    - "!design_EN/"
    - "!design_JA/"
    - "!docs/design_EN/"

website:
  title: "Math Knowledge Graph"
  favicon: favicon.ico
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Algebra"
        href: content/en/algebra/index.qmd
      - text: "Analysis"
        href: content/en/analysis/index.qmd
      - text: "Topology"
        href: content/en/topology/index.qmd
      - text: "Geometry"
        href: content/en/geometry/index.qmd
      - text: "Category Theory"
        href: content/en/category-theory/index.qmd
      - text: "Combinatorics"
        href: content/en/combinatorics/index.qmd
      - text: "Logic & Set Theory"
        href: content/en/logic-set-theory/index.qmd
      - text: "Number Theory"
        href: content/en/number-theory/index.qmd
      - text: "Probability & Statistics"
        href: content/en/probability-statistics/index.qmd
      - text: "Search"
        href: search.qmd
      - text: "Visualizations"
        href: visualizations.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "🌐 日本語"
        href: ../ja/index.html
      - icon: github
        href: https://github.com/RK0429/ModernMath
        aria-label: github
  sidebar:
    - id: algebra
      title: "Algebra"
      contents:
        - content/en/algebra/*.qmd
    - id: analysis
      title: "Analysis"
      contents:
        - content/en/analysis/*.qmd
    - id: topology
      title: "Topology"
      contents:
        - content/en/topology/*.qmd
    - id: geometry
      title: "Geometry"
      contents:
        - content/en/geometry/*.qmd
    - id: category-theory
      title: "Category Theory"
      contents:
        - content/en/category-theory/*.qmd
    - id: combinatorics
      title: "Combinatorics"
      contents:
        - content/en/combinatorics/*.qmd
    - id: logic-set-theory
      title: "Logic & Set Theory"
      contents:
        - content/en/logic-set-theory/*.qmd
    - id: number-theory
      title: "Number Theory"
      contents:
        - content/en/number-theory/*.qmd
    - id: probability-statistics
      title: "Probability & Statistics"
      contents:
        - content/en/probability-statistics/*.qmd
  page-footer:
    center: |
      Mathematics Knowledge Graph Wiki - Built with Quarto and RDF

format:
  html:
    theme: cosmo
    css:
      - ../../styles.css
      - ../../styles-multilingual.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-copy: true
    code-overflow: wrap
    html-math-method: mathjax
    lang: en
    include-in-header:
      - text: |
          <script>
            window.siteLanguage = 'en';
            window.alternateLanguage = 'ja';
            window.alternateLanguageUrl = '../ja/';
            // Calculate the correct path to js directory based on current location
            (function() {
              var path = window.location.pathname;
              var pathParts = path.split('/');
              var basePath = '';

              // Remove empty parts
              pathParts = pathParts.filter(function(part) { return part; });

              // Find the FIRST occurrence of the language directory ('en' or 'ja')
              var langIndex = -1;
              for (var i = 0; i < pathParts.length; i++) {
                if (pathParts[i] === 'en' || pathParts[i] === 'ja') {
                  langIndex = i;
                  break;
                }
              }

              if (langIndex >= 0) {
                // Calculate how many directories deep we are from the language root
                // Don't count the HTML file itself
                var dirsAfterLang = pathParts.length - langIndex - 2;

                // Build the path with the correct number of '../'
                for (var k = 0; k < dirsAfterLang; k++) {
                  basePath += '../';
                }
              }

              basePath = basePath || './';
              var script = document.createElement('script');
              script.src = basePath + 'js/language-switcher.js';
              script.defer = true;
              document.head.appendChild(script);
            })();
          </script>
    mathjax:
      tags: ams
      macros:
        R: '\mathbb{R}'
        Z: '\mathbb{Z}'
        N: '\mathbb{N}'
        C: '\mathbb{C}'
        Q: '\mathbb{Q}'
        implies: '\Rightarrow'
        iff: '\Leftrightarrow'

filters:
  - math-environments
  - graph-viz
  - translation-metadata

execute:
  freeze: auto

bibliography: references.bib

resources:
  - knowledge_graph.ttl
  - .nojekyll
  - output/interactive
  - output/d3-data
  - js
