name: "🐞 Bug report"
description: "Something isn’t working as expected? Let us know!"
title: "[Bug]: <short description>"
labels: ["bug", "needs-triage"]
assignees: ["@repo‑maintainer"]
projects: ["org/1"]           # optional
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out **all** mandatory fields.

  - type: input
    id: reproduction_link
    attributes:
      label: Minimal reproduction
      description: "Public repo / Codesandbox / steps to reproduce."
      placeholder: "https://..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Be precise – numbered list preferred."
      placeholder: |
        1. `git clone ...`
        2. `npm install`
        3. `npm start`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: "It should ..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      placeholder: "Instead it ..."
    validations:
      required: true

  - type: dropdown
    id: environment_os
    attributes:
      label: Operating system
      options: ["macOS", "Windows", "Linux", "Other"]
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package / CLI version
      placeholder: "e.g. v2.3.1"
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Self‑service checks
      options:
        - label: I have searched the existing issues
          required: true
        - label: I have read the contributing guidelines
          required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output / screenshots
      render: shell
