blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/RK0429/ModernMath/discussions
    about: "If you're not sure whether this is a bug, start a discussion instead."

# Template ordering in chooser UI
# The page-issue template will be used when accessed via Report Issue buttons on pages
