blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/<owner>/<repo>/discussions
    about: "If you’re not sure whether this is a bug, start a discussion instead."

# Optional: re‑order template buttons in chooser UI
# and set a default template for ‘New issue’
