name: "✨ Feature request"
description: "Suggest an idea to improve this project."
title: "[Feat]: <short title>"
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Before opening**: check existing issues and discussions for similar ideas.

  - type: textarea
    id: context
    attributes:
      label: Problem statement
      description: "What problem will this feature solve? Who benefits?"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "Describe the API, UX, or behaviour you envision."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "e.g. Use existing plug‑in X..."
    validations:
      required: false
